In [1]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.externals import joblib
from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [4]:
# 学習用のデータを読み込み
data = pd.read_csv("./task1.csv", sep=",")
train_data, test_data = train_test_split(data, test_size=0.15, shuffle=True)

X = train_data.loc[:, ['x', 'y']]#.as_matrix()
y = train_data['target']#.as_matrix()

# 学習
clf = MLPClassifier(hidden_layer_sizes=(20, 10,),alpha=True,random_state=0,max_iter=10000)
clf.fit(X, y)

# テスト用データ定義
# 学習結果の検証（テスト用データx1, x2を入力）
X_test = test_data.loc[:, ['x', 'y']]#.as_matrix()
y_predict = clf.predict(X_test)
y_label = test_data['target']

# 検証結果の表示
#print("検証結果：", y_predict)
#print("pred:", y_predict, "label:", y_label)
print(classification_report(np.hstack(y_label), np.hstack(y_predict)))
print("accuracy:", accuracy_score(y_label, y_predict))
print("confusion_matrix\n",confusion_matrix(y_label, y_predict))

             precision    recall  f1-score   support

          0       0.97      0.97      0.97       738
          1       0.92      0.95      0.93       765
          2       0.97      0.94      0.95       747

avg / total       0.95      0.95      0.95      2250

accuracy: 0.9511111111111111
confusion_matrix
 [[715  21   2]
 [ 22 725  18]
 [  2  45 700]]
